CreateKey interactor
Kuama-IT/kerbero pull request #124
Opened 2022-11-18 16:04 UTC by salvanicola

- Created entity
- Created interactor
- New Errors key-related
- Tests
Closes #70, closes #69

2022-11-18 21:11 UTC, vash72 commented on web-api/src/Kerbero.Domain/Keys/Entities/Key.cs
> +public class Key
you cannot go wrong with this name

2022-11-21 13:00 UTC, kuamanet requested changes

2022-11-21 13:18 UTC, salvanicola commented on web-api/src/Kerbero.Domain/SmartLockKeys/Entities/SmartLockKey.cs
> +	public int UsingCounter { get; set; }
the first one

2022-11-21 16:54 UTC, kuamanet approved these changes

2022-11-21 16:55 UTC, merged