integration tests for nuki smartlock download from API
Kuama-IT/kerbero pull request #25
Opened 2022-10-25 07:30 UTC by salvanicola

2022-10-25 10:11 UTC, vash72 requested changes

2022-10-25 10:11 UTC, vash72 commented on tests/Kerbero.Integration.Tests/NukiSmartLocksListIntegrationTests.cs
> +	private class KerberoWebApplicationFactory<TStartup>
```suggestion
	private class KerberoWebApplicationFactory<TStartup>
```
perchè privata, sinceramente credo sia riutilizzabile in molti test

2022-10-25 10:11 UTC, vash72 commented on tests/Kerbero.Integration.Tests/Utilities.cs
> +	public static readonly object NukiJsonSmartlockResponse = new
come faccio a capire da che endpoint torna questo mock? perchè non usi direttamente il json come fixture invece di fare una class e mettarla so utilities?

2022-10-25 10:11 UTC, vash72 commented on tests/Kerbero.Integration.Tests/NukiSmartLocksListIntegrationTests.cs
> +		_httpTest.RespondWith(status: 401, body: System.Text.Json.JsonSerializer.Serialize(new
```suggestion
		_httpTest.RespondWith(status: 401, body: JsonSerializer.Serialize(new
```

2022-10-25 10:11 UTC, vash72 commented on tests/Kerbero.Integration.Tests/NukiSmartLocksListIntegrationTests.cs
> +		GC.SuppressFinalize(this);
```suggestion
		GC.SuppressFinalize(this);
```
perchè necessario chiamare il garbage collector nel teardown del test?

2022-10-25 11:02 UTC, salvanicola commented on tests/Kerbero.Integration.Tests/Utilities.cs
> +	public static readonly object NukiJsonSmartlockResponse = new
Perché è utilizzata da più test

2022-10-26 15:14 UTC, vash72 requested changes

2022-10-26 15:14 UTC, vash72 commented on tests/JsonData/get-nuki-smartlock-response.json
> +{
tests/fixtures/json/get-nuki-smartlock-response.json

2022-10-26 15:14 UTC, vash72 commented on tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockExternalRepositoryTests.cs
> +        using var streamReader = new StreamReader("get-nuki-smartlock-response.json");
credo ti basti usare File.ReadAllText

2022-10-27 07:14 UTC, vash72 requested changes

2022-10-27 07:14 UTC, vash72 commented on tests/Kerbero.Infrastructure.Tests/NukiActions/Repositories/NukiSmartLockExternalRepositoryTests.cs
> +        using var streamReader = new StreamReader("JsonData/get-nuki-smartlock-response.json");
```suggestion
        using var streamReader = new StreamReader("JsonData/get-nuki-smartlock-response.json");
```
why not File sync methods?

2022-10-27 07:14 UTC, vash72 commented on tests/Kerbero.Integration.Tests/Utilities.cs
> +		db.NukiAccounts.AddRange(GetSeedingMessages());
```suggestion
		db.NukiAccounts.AddRange(GetSeedingMessages());
```
per il momento puo andare, pero in generale credo tu voglia seedare ogni volta in maniera diversa in base al test

2022-10-27 14:39 UTC, vash72 requested changes

2022-10-27 14:39 UTC, vash72 commented on tests/Kerbero.Integration.Tests/Utilities.cs
> +public class Utilities
```suggestion
public static class KerberoIntegrationTestUtils
```

2022-10-27 14:39 UTC, vash72 commented on tests/Kerbero.Integration.Tests/Utilities.cs
> +	public Utilities()
utilities class ar mean to be **pure**, remove the ctor and fields

2022-10-28 07:37 UTC, giovanni-nic-kuama approved these changes

2022-10-28 07:55 UTC, merged